### ISSUE TITLE
Pipelinescan and Eclipse

### ISSUE THREAD

**Issue by tXambe** [frodriguezc/pipelinescan#1]
Hello,

I will know if I can launch/execute pipelinescan form Eclipse

A greeting and thanks

**Comment by frodriguezc** [comment]
Sure! you can configure as an action in "External Tools Configuration", then "Create, manage, and run configurations", and then "Run a program". Set the Location and Working Directory as the project root and your workspace, then call the script in the Arguments section.
You should get something like this:
<img width="688" alt="Captura de Pantalla 2020-08-06 a la(s) 00 12 36" src="https://user-images.githubusercontent.com/14891920/89489933-8f18c000-d779-11ea-84ee-e3be0022bcb6.png">
Let me know if you have any issues with that.

Thanks and Cheers!
